// <auto-generated />
using System;
using CIS_296_Final_Project.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CIS_296_Final_Project.Migrations
{
    [DbContext(typeof(CharacterContext))]
    partial class CharacterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CIS_296_Final_Project.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OgTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("CharacterId");

                    b.HasIndex("OgTypeId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            Name = "Sonic the Hedgehog",
                            OgTypeId = "G",
                            Origin = "Sonic the Hedgehog (1991)",
                            Year = 1991
                        },
                        new
                        {
                            CharacterId = 2,
                            Name = "Miles \"Tails\" Prower",
                            OgTypeId = "G",
                            Origin = "Sonic the Hedgehog 2",
                            Year = 1992
                        },
                        new
                        {
                            CharacterId = 3,
                            Name = "Knuckles the Echidna",
                            OgTypeId = "G",
                            Origin = "Sonic the Hedgehog 3",
                            Year = 1993
                        },
                        new
                        {
                            CharacterId = 4,
                            Name = "Amy Rose",
                            OgTypeId = "M",
                            Origin = "ソニック·ザ·ヘッジホッグ",
                            Year = 1992
                        });
                });

            modelBuilder.Entity("CIS_296_Final_Project.Models.OgType", b =>
                {
                    b.Property<string>("OgTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OgTypeId");

                    b.ToTable("OgTypes");

                    b.HasData(
                        new
                        {
                            OgTypeId = "A",
                            Name = "Anime"
                        },
                        new
                        {
                            OgTypeId = "C",
                            Name = "Comic"
                        },
                        new
                        {
                            OgTypeId = "F",
                            Name = "Movie"
                        },
                        new
                        {
                            OgTypeId = "G",
                            Name = "Game"
                        },
                        new
                        {
                            OgTypeId = "M",
                            Name = "Manga"
                        },
                        new
                        {
                            OgTypeId = "S",
                            Name = "Cartoon"
                        });
                });

            modelBuilder.Entity("CIS_296_Final_Project.Models.Character", b =>
                {
                    b.HasOne("CIS_296_Final_Project.Models.OgType", "OgType")
                        .WithMany()
                        .HasForeignKey("OgTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OgType");
                });
#pragma warning restore 612, 618
        }
    }
}
